---
version: '2'

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gocyclo
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
