---
run:
  timeout: 5m
  issues-exit-code: 1

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 15
  lll:
    line-length: 120

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
