// Package testutil provides shared testing utilities for pinentry-proton tests
package testutil

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

// MockPassCLI provides a sophisticated mock implementation of pass-cli
type MockPassCLI struct {
	// vault[vault][item][field] = value
	vault map[string]map[string]map[string]string

	// Simulation options
	latency     time.Duration
	failureRate float64

	// Call tracking
	callLog []MockCall
	mu      sync.Mutex
}

// MockCall represents a logged call to the mock
type MockCall struct {
	Timestamp time.Time
	Command   string
	Args      []string
	Result    string
	Error     error
}

// NewMockPassCLI creates a new mock pass-cli with default test data
func NewMockPassCLI() *MockPassCLI {
	mock := &MockPassCLI{
		vault:       make(map[string]map[string]map[string]string),
		latency:     0,
		failureRate: 0.0,
		callLog:     []MockCall{},
	}

	// Add default test item
	mock.AddItem("test", "mock-item", "password", "424242")

	return mock
}

// AddItem adds an item to the mock vault
func (m *MockPassCLI) AddItem(vault, item, field, value string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.vault[vault] == nil {
		m.vault[vault] = make(map[string]map[string]string)
	}
	if m.vault[vault][item] == nil {
		m.vault[vault][item] = make(map[string]string)
	}
	m.vault[vault][item][field] = value
}

// SetLatency sets the simulated network latency
func (m *MockPassCLI) SetLatency(duration time.Duration) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.latency = duration
}

// SetFailureRate sets the simulated failure rate (0.0-1.0)
func (m *MockPassCLI) SetFailureRate(rate float64) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if rate < 0 {
		rate = 0
	}
	if rate > 1 {
		rate = 1
	}
	m.failureRate = rate
}

// GenerateCLI creates a shell script executable that acts as mock pass-cli
func (m *MockPassCLI) GenerateCLI(t *testing.T, path string) {
	t.Helper()

	// Create parent directory if needed
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil { //nolint:gosec // G301: Standard directory permissions for test fixtures
		t.Fatalf("Failed to create directory for mock CLI: %v", err)
	}

	// Generate shell script that reads from a data file
	dataFile := path + ".data"
	m.writeDataFile(t, dataFile)

	script := fmt.Sprintf(`#!/bin/bash
# Mock pass-cli generated by testutil
# Data file: %s

# Simulate latency if configured
LATENCY_FILE="%s.latency"
if [ -f "$LATENCY_FILE" ]; then
    LATENCY=$(cat "$LATENCY_FILE")
    sleep "$LATENCY"
fi

# Simulate failures if configured
FAILURE_FILE="%s.failure"
if [ -f "$FAILURE_FILE" ]; then
    FAILURE_RATE=$(cat "$FAILURE_FILE")
    RAND=$RANDOM
    if [ $(($RAND %% 100)) -lt $(echo "$FAILURE_RATE * 100" | bc -l | cut -d. -f1) ]; then
        echo "Error: Simulated failure" >&2
        exit 1
    fi
fi

# Parse arguments
COMMAND=""
SUBCOMMAND=""
ITEM_REF=""
FIELD="password"

while [[ $# -gt 0 ]]; do
    case "$1" in
        item)
            COMMAND="item"
            shift
            ;;
        get)
            SUBCOMMAND="get"
            shift
            ;;
        --field)
            shift
            FIELD="$1"
            shift
            ;;
        *)
            if [ -z "$ITEM_REF" ]; then
                ITEM_REF="$1"
            fi
            shift
            ;;
    esac
done

# Handle item get command
if [ "$COMMAND" = "item" ] && [ "$SUBCOMMAND" = "get" ]; then
    # Parse vault/item from reference
    VAULT=$(echo "$ITEM_REF" | cut -d/ -f1)
    ITEM=$(echo "$ITEM_REF" | cut -d/ -f2)

    # Look up in data file
    VALUE=$(grep "^$VAULT/$ITEM/$FIELD=" "%s" | cut -d= -f2-)

    if [ -z "$VALUE" ]; then
        echo "Error: Item not found: $VAULT/$ITEM/$FIELD" >&2
        exit 1
    fi

    echo "$VALUE"
    exit 0
fi

# Unknown command
echo "Error: Unknown command" >&2
exit 1
`, dataFile, path, path, dataFile)

	if err := os.WriteFile(path, []byte(script), 0755); err != nil { //nolint:gosec // G306: Executable script needs 0755
		t.Fatalf("Failed to write mock CLI script: %v", err)
	}

	// Write latency file if configured
	if m.latency > 0 {
		latencyFile := path + ".latency"
		latencyStr := fmt.Sprintf("%f", m.latency.Seconds())
		if err := os.WriteFile(latencyFile, []byte(latencyStr), 0644); err != nil { //nolint:gosec // G306: Data file, 0644 is appropriate
			t.Fatalf("Failed to write latency file: %v", err)
		}
	}

	// Write failure rate file if configured
	if m.failureRate > 0 {
		failureFile := path + ".failure"
		failureStr := fmt.Sprintf("%f", m.failureRate)
		if err := os.WriteFile(failureFile, []byte(failureStr), 0644); err != nil { //nolint:gosec // G306: Data file, 0644 is appropriate
			t.Fatalf("Failed to write failure file: %v", err)
		}
	}
}

// writeDataFile writes the vault data to a file that the mock CLI reads
func (m *MockPassCLI) writeDataFile(t *testing.T, path string) {
	t.Helper()

	var sb strings.Builder
	m.mu.Lock()
	for vault, items := range m.vault {
		for item, fields := range items {
			for field, value := range fields {
				sb.WriteString(fmt.Sprintf("%s/%s/%s=%s\n", vault, item, field, value))
			}
		}
	}
	m.mu.Unlock()

	if err := os.WriteFile(path, []byte(sb.String()), 0644); err != nil { //nolint:gosec // G306: Data file, 0644 is appropriate
		t.Fatalf("Failed to write data file: %v", err)
	}
}

// GetCallLog returns the call log
func (m *MockPassCLI) GetCallLog() []MockCall {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Return a copy to avoid race conditions
	log := make([]MockCall, len(m.callLog))
	copy(log, m.callLog)
	return log
}

// Reset clears the call log and resets state
func (m *MockPassCLI) Reset() {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.callLog = []MockCall{}
	m.latency = 0
	m.failureRate = 0.0
}

// CreateMockPassCLI is a helper function that creates a mock CLI and returns its path
func CreateMockPassCLI(t *testing.T, vault, item, field, password string) string {
	t.Helper()

	mock := NewMockPassCLI()
	mock.AddItem(vault, item, field, password)

	tmpDir := t.TempDir()
	cliPath := filepath.Join(tmpDir, "mock-pass-cli")
	mock.GenerateCLI(t, cliPath)

	return cliPath
}

// CreateMockPassCLIWithError creates a mock CLI that always fails
func CreateMockPassCLIWithError(t *testing.T, errorMessage string) string {
	t.Helper()

	tmpDir := t.TempDir()
	cliPath := filepath.Join(tmpDir, "mock-pass-cli-error")

	script := fmt.Sprintf(`#!/bin/bash
echo "%s" >&2
exit 1
`, errorMessage)

	if err := os.WriteFile(cliPath, []byte(script), 0755); err != nil { //nolint:gosec // G306: Executable script needs 0755
		t.Fatalf("Failed to create error mock CLI: %v", err)
	}

	return cliPath
}

// CreateMockPassCLIWithTimeout creates a mock CLI that times out
func CreateMockPassCLIWithTimeout(t *testing.T, timeout time.Duration) string {
	t.Helper()

	tmpDir := t.TempDir()
	cliPath := filepath.Join(tmpDir, "mock-pass-cli-timeout")

	script := fmt.Sprintf(`#!/bin/bash
sleep %d
echo "timeout"
`, int(timeout.Seconds())+1)

	if err := os.WriteFile(cliPath, []byte(script), 0755); err != nil { //nolint:gosec // G306: Executable script needs 0755
		t.Fatalf("Failed to create timeout mock CLI: %v", err)
	}

	return cliPath
}
